dist: focal
language: java
before_install:
  - "export DISPLAY=:99.0"
  - "Xvfb :99 -screen 0 1024x768x24 &"
jobs:
  include:
    - stage: "Test"
      script: ./gradlew test
      jdk: openjdk21
    - script: ./gradlew test
      jdk: openjdk25
    - stage: "Static Analysis"
      script: ./gradlew staticAnalysis
      jdk: openjdk21
    - script: ./gradlew staticAnalysis
      jdk: openjdk25
